version: "3.9"

networks:
  data-service-network
  
services:
  mongodb_container:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: database
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      data-service-network
  
  review-service:
    depends_on:
      - mongodb_container
    image: miverboven/review-service-ex
    ports:
      - "8052:8052"
    networks:
      data-service-network

volumes:
  mongodb_data_container:
