version: "3.9"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: database
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
  
  book-info-service:
    depends_on:
      - mongodb_container
    image: miverboven/review-service-ex
    ports:
      - '8051:8051'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mongodb://mongodb_container:27017/database?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false

volumes:
  mongodb_data_container:
